the increment 14 is completed
MisterMaks/go-yandex-shortener pull request #15
Opened 2024-07-07 20:13 UTC by MisterMaks

2024-07-10 21:48 UTC, avhitrov requested changes
Реализация отличная, но есть несколько мелких вопросов, отмечены комментариями к коду.

2024-07-10 21:48 UTC, avhitrov commented on internal/app/delivery/http.go
> +	userID := r.Context().Value(usecase.UserIDKey).(uint)
А почему в остальных функциях используется `userID, err := usecase.GetContextUserID(r.Context())` с проверкой и выставлением `StatusUnauthorized`, а здесь просто вытаскивается из контекста?

2024-07-10 21:48 UTC, avhitrov commented on internal/app/delivery/http.go
> +	err = ah.AppUsecase.SendDeleteUserURLsInChan(userID, req)
`err` у этой функции всегда nil. Для чего ее объявлять, как возвращающую error и здесь пытаться как-то эту несуществующую ошибку обработать?

2024-07-10 21:48 UTC, avhitrov commented on internal/app/usecase/usecase.go
> +func (au *AppUsecase) SendDeleteUserURLsInChan(userID uint, urlIDs []string) error {
```suggestion
func (au *AppUsecase) SendDeleteUserURLsInChan(userID uint, urlIDs []string) {
```

2024-07-10 21:48 UTC, avhitrov commented on internal/app/delivery/http.go
> +	SendDeleteUserURLsInChan(userID uint, urlIDs []string) error
```suggestion
	SendDeleteUserURLsInChan(userID uint, urlIDs []string)
```

2024-07-10 21:48 UTC, avhitrov commented on internal/app/usecase/usecase.go
> +			urls = nil
```suggestion
			urls = urls[:0]
```
А можно еще и объявить urls через make с преаллокацией.
https://t.me/bushigo/11
https://t.me/bushigo/12

2024-07-11 21:09 UTC, MisterMaks commented on internal/app/delivery/http.go
> +	userID := r.Context().Value(usecase.UserIDKey).(uint)
Поправил
Я реализовал функцию `userID, err := usecase.GetContextUserID(r.Context())` после того, как сделал новые API методы и забыл поправить в этих методах.

2024-07-11 21:15 UTC, MisterMaks commented on internal/app/delivery/http.go
> +	err = ah.AppUsecase.SendDeleteUserURLsInChan(userID, req)
Поправил.
Это привычка - если функция используется в других модулях - всегда возвращать ошибку. Мне на одном проекте посоветовали так делать, вот с тех пор я так и делаю)

2024-07-11 21:20 UTC, MisterMaks commented on internal/app/usecase/usecase.go
> +func (au *AppUsecase) SendDeleteUserURLsInChan(userID uint, urlIDs []string) error {
Поправил

2024-07-11 21:20 UTC, MisterMaks commented on internal/app/delivery/http.go
> +	SendDeleteUserURLsInChan(userID uint, urlIDs []string) error
Поправил

2024-07-11 21:22 UTC, MisterMaks commented on internal/app/usecase/usecase.go
> +			urls = nil
Поправил
Спасибо за канал, подписался)

2024-07-14 23:06 UTC, avhitrov approved these changes
Все отлично!

2024-07-15 13:00 UTC, merged