the increment 5 is completed
MisterMaks/go-yandex-shortener pull request #5
Opened 2024-05-06 21:11 UTC by MisterMaks

2024-05-12 18:43 UTC, avhitrov requested changes
В общем, годный, рабочий вариант. Есть не вполне верное поведение при инициализации конфигурации. И есть пара замечаний по оптимизации работы стораджа. Все в комментариях к коду.

2024-05-12 18:43 UTC, avhitrov commented on cmd/shortener/config.go
> +	//     - Адрес должен быть равен адресу в поле ServerAddress
Не должен!

Более того, в случае неуказания этого адреса через окружение или командную строку необходимо какое-то внятное умолчание, например `http://localhost:8080/`. В текущей реализации если при запуске указать валидное значение `-a :8080`, в ответах будет выставлен невалидный базовый адрес `http://:8080/`.

2024-05-12 18:43 UTC, avhitrov commented on internal/app/repo/inmem.go
> +	}
Не нужна здесь эта параноидальная проверка. Если уж хочется быть уверенным, что структура `ari.mu` инициализирована, можно в типе объявить ее, как `sync.RWMutex`, а не как ссылку.

2024-05-12 18:43 UTC, avhitrov commented on internal/app/repo/inmem.go
> +	ari.mu.RLock()
Достаточно одной блокировки на запись на всю функцию. Если предполагается запись в защищаемую структуру, то просто ставится 
```
ari.mu.Lock()
defer ari.mu.Unlock()
```
в начале функции. Если бьемся за скорость и производительность, лучше тогда слайс заменить на мапу. На количестве значений более сотни мапа начинает обгонять по скорости доступа слайс.

2024-05-13 18:26 UTC, MisterMaks commented on cmd/shortener/config.go
> +	//     - Адрес должен быть равен адресу в поле ServerAddress
Поправил. Надеюсь я всё правильно понял. Теперь: `Адрес должен быть равен адресу в поле ServerAddress` - этого нет, убрал. Адреса могут быть различными

2024-05-13 18:26 UTC, MisterMaks commented on internal/app/repo/inmem.go
> +	}
Поменял на `sync.RWMutex`

2024-05-13 18:27 UTC, mistermaks97 commented on internal/app/repo/inmem.go
> +	ari.mu.RLock()
Оставил только:
```
ari.mu.Lock()
defer ari.mu.Unlock()
```

2024-05-15 22:17 UTC, avhitrov approved these changes
Все замечания устранены, аппрув! Просьба в будущем не резолвить комментарии в непринятом ПР - они нужны мне для пошаговой проверки моих вопросов.

2024-05-15 22:32 UTC, merged